version: '3.8'  # Use the latest version of Docker Compose

services:
  database:
    container_name: database
    image: postgres:latest  # Specify the PostgreSQL image version explicitly
    env_file:
      - ./backend-nest/.env  # Load environment variables from a file
    ports:
      - "5433:5432"
    volumes:
      - database_data:/home/ripa/postgresql/data
    networks:
      - app_network  # Use a user-defined network for better isolation

  backend:
    container_name: backend
    build:
      context: ./backend-nest
      dockerfile: Dockerfile  # You don't need quotes around the Dockerfile path
    ports:
      - "3000:3000"
    env_file:
      ./backend-nest/.env # Load environment variables from a file
    depends_on:
      - database  # Ensure the backend service starts after the database
    networks:
      - app_network
    volumes:
      - backend-code:/app # Volume for sharing the backend's code from host to container

#   frontend:
#     container_name: frontend
#     build:
#       context: ./frontend-vue
#       dockerfile: Dockerfile
#     depends_on:
#       - backend
#     networks:
#       - app_network

volumes:
  backend-code:
    driver: local
    name: backend-code
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/backend-nest
  database_data: {}

networks:
  app_network: {}